### PR TITLE
removed remHook onProfileLoading

### LINKED ISSUE #103: Hook race condition?
#### Problem description
This pertains to PR #99:

There  should be a short delay before remHook can be called. Below test shows that all hooks are registered and removed correctly, but the hook next in line based on the addon sort order is not involked or blocked.
```
Load: A
Load: B (nm)
Load: C
Load: D
Run: A
Run: B
Rm: B
Run: D
Hooks: [A, C, D]
(addon C was blocked)
```
So the current version of nm (v2.3.2) blocks the addon next in line from triggering "profileLoaded". Adding in a delay by moving remHook to delayLoader() resolved this issue.
```
def delayedLoader():
    from .night_mode import NightMode
    night_mode = NightMode()
    night_mode.load()
    remHook("profileLoaded", onProfileLoaded)

def onProfileLoaded():
    # remHook("profileLoaded", onProfileLoaded)
```
I'll hold off on the updates and see if other issues arise. But so far, it seems most of the previous addon conflicts have been resolved. Comments and suggestions are welcomed.

### TODO:
Rewrite to avoid race conditions with hooks.

#### Checklist

*Please put x inside brackets if following sentences apply to you:*

 - [X ] I verified that I use the lastest add-on version,
 - [X ] I verified that I use the lastest Anki version,
 - [X ] I tried to disable other add-ons to find the culprit,
 - [X ] I checked if anyone reported this problem before, as well as Known issues section on add-ons page,
 - [X ] My issue is solved when holding shift while starting Anki.
 
#### Information about your Anki Setup

This is tested on anki 2.0.52, 2.1.15, 2.1.19, 2.1.20b5 with nightmode v2.3.2

### PR DESCRIPTION
**Pull request by lovac42**
Replaced creative hooks with standard global variable to check for startup profile.

fixes #103 #104

### CODE REVIEW

**Comment by glutanimate** [comment]
Thanks for the quick response to this, @lovac42 . I can confirm that this PR fixes #103 for add-ons like Hierarchical Tags & many others that were affected by it. @krassowski if we could fast track this somehow that would be really nice as the number of bug reports about this to other add-ons is rising quickly.

Obviously this was impossible to predict a few weeks ago, but with Anki soon shipping with a native night mode, I think it would be prudent to hold off on any further major changes to Night Mode's behavior, especially in regards to add-on loading order or other cross-addon interactions. Having that predictability in this transitional period would be important I think.

**Comment by lovac42** [comment]
Sorry about that glutanimate. With NM built in to anki, this addon has been deprecated, so this is just cleaning things up that was not previously detected.

Perhaps a safer approach is to just revert back to the original __init__.py file and not take any risks? With native NM in .20, fixing the original issue is of less importance now.

**Comment by krassowski** [comment]
@glutanimate fast-tracked as requested. @lovac42 thank you!

**Comment by glutanimate** [comment]
Sorry, guys. Meant to reply earlier, but I've been a bit under the weather these past few days.

@krassowski Thanks a bunch for fast-tracking this. Much appreciated!

@lovac42 I think the add-on is in a good state now. If we had known about Anki's native NM in advance, it would have been better to keep things as they are – but since we're already past that, I think we should just roll with the changes. Even with .20 out soon, it will likely still take a while until the majority of the userbase upgrades. To have a solution that fixes the add-on incompatibilities of old in this transitional time is a great boon in my mind. These minor hiccups aside, which were difficult to foresee, I think you did a great job at addressing the problem, so kudos for that!

**Pull request merged**
